"""catalog: standards, disclosures, dimensions, metric definitions

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 00:02:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SCOPED = ("dimension", "dimension_value", "metric_definition", "metric_dimension")

# Global rows (organization_id NULL) are seeded by the owner from backend/catalog/*.yaml; the app
# can only read them. Tenants read global rows plus their own and write only their own.
# ENABLE without FORCE: the seeder runs as the owner and must write global rows.
SECURITY: tuple[str, ...] = (
    "GRANT SELECT ON standard, disclosure TO gri_app",
    "CREATE TRIGGER metric_definition_set_updated_at BEFORE UPDATE ON metric_definition"
    " FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    *(
        statement
        for table in _SCOPED
        for statement in (
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
            f"CREATE POLICY catalog_select ON {table} FOR SELECT"
            " USING (organization_id IS NULL OR organization_id = app_current_org_id())",
            f"CREATE POLICY catalog_insert ON {table} FOR INSERT"
            " WITH CHECK (organization_id = app_current_org_id())",
            f"CREATE POLICY catalog_update ON {table} FOR UPDATE"
            " USING (organization_id = app_current_org_id())"
            " WITH CHECK (organization_id = app_current_org_id())",
        )
    ),
    # Structure (codes, types, units, rules, links) is never updatable by the app.
    "GRANT SELECT, INSERT, UPDATE (name) ON dimension TO gri_app",
    "GRANT SELECT, INSERT, UPDATE (label, sort_order, retired_at) ON dimension_value TO gri_app",
    "GRANT SELECT, INSERT, UPDATE (name, description, requirement, sort_order, retired_at)"
    " ON metric_definition TO gri_app",
    "GRANT SELECT, INSERT ON metric_dimension TO gri_app",
    # A row may reference global rows or rows of its own organization, never another tenant's.
    # SECURITY DEFINER so the lookups see the referenced row even when RLS would hide it.
    """
    CREATE FUNCTION catalog_check_scope() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
    DECLARE
        ref_org uuid;
    BEGIN
        IF TG_TABLE_NAME = 'metric_dimension' THEN
            SELECT organization_id INTO ref_org
            FROM metric_definition WHERE id = NEW.metric_definition_id;
            IF ref_org IS DISTINCT FROM NEW.organization_id THEN
                RAISE EXCEPTION 'a metric dimension must have the same scope as its metric'
                    USING ERRCODE = 'check_violation', CONSTRAINT = 'catalog_scope';
            END IF;
        END IF;

        SELECT organization_id INTO ref_org FROM dimension WHERE id = NEW.dimension_id;
        IF ref_org IS NOT NULL AND ref_org IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'dimension % belongs to another organization', NEW.dimension_id
                USING ERRCODE = 'check_violation', CONSTRAINT = 'catalog_scope';
        END IF;
        RETURN NEW;
    END
    $$
    """,
    "REVOKE ALL ON FUNCTION catalog_check_scope() FROM PUBLIC",
    *(
        f"CREATE TRIGGER {table}_check_scope BEFORE INSERT OR UPDATE ON {table}"
        " FOR EACH ROW EXECUTE FUNCTION catalog_check_scope()"
        for table in ("dimension_value", "metric_dimension")
    ),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_date', name=op.f('ck_standard_dates_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard')),
    sa.UniqueConstraint('code', 'version', name=op.f('uq_standard_code_version'))
    )
    op.create_table('dimension',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(organization_id IS NULL) = NOT starts_with(code, 'custom.')", name=op.f('ck_dimension_code_scope')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_dimension_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dimension'))
    )
    op.create_index('uq_dimension_global_code', 'dimension', ['code'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_index('uq_dimension_tenant_code', 'dimension', ['organization_id', 'code'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_table('disclosure',
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standard.id'], name=op.f('fk_disclosure_standard_id_standard')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosure')),
    sa.UniqueConstraint('standard_id', 'code', name=op.f('uq_disclosure_standard_id_code'))
    )
    op.create_table('dimension_value',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('dimension_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(organization_id IS NULL) = NOT starts_with(code, 'custom.')", name=op.f('ck_dimension_value_code_scope')),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], name=op.f('fk_dimension_value_dimension_id_dimension')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_dimension_value_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dimension_value'))
    )
    op.create_index('uq_dimension_value_global_code', 'dimension_value', ['dimension_id', 'code'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_index('uq_dimension_value_tenant_code', 'dimension_value', ['dimension_id', 'organization_id', 'code'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_table('metric_definition',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('disclosure_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(data_type IN ('decimal', 'integer')) = (unit IS NOT NULL)", name=op.f('ck_metric_definition_unit_iff_numeric')),
    sa.CheckConstraint("(organization_id IS NULL) = NOT starts_with(code, 'custom.')", name=op.f('ck_metric_definition_code_scope')),
    sa.CheckConstraint("data_type IN ('decimal', 'integer', 'boolean', 'text', 'choice', 'date')", name=op.f('ck_metric_definition_data_type_valid')),
    sa.CheckConstraint("jsonb_typeof(validation_rules) = 'object'", name=op.f('ck_metric_definition_rules_object')),
    sa.CheckConstraint("requirement IN ('required', 'required_if_applicable', 'optional')", name=op.f('ck_metric_definition_requirement_valid')),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosure.id'], name=op.f('fk_metric_definition_disclosure_id_disclosure')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_metric_definition_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definition'))
    )
    op.create_index('uq_metric_definition_global_code', 'metric_definition', ['code'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_index('uq_metric_definition_tenant_code', 'metric_definition', ['organization_id', 'code'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_table('metric_dimension',
    sa.Column('metric_definition_id', sa.Uuid(), nullable=False),
    sa.Column('dimension_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], name=op.f('fk_metric_dimension_dimension_id_dimension')),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definition.id'], name=op.f('fk_metric_dimension_metric_definition_id_metric_definition')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_metric_dimension_organization_id_organization')),
    sa.PrimaryKeyConstraint('metric_definition_id', 'dimension_id', name=op.f('pk_metric_dimension'))
    )
    # ### end Alembic commands ###

    for statement in SECURITY:
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_dimension')
    op.drop_index('uq_metric_definition_tenant_code', table_name='metric_definition', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('uq_metric_definition_global_code', table_name='metric_definition', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_table('metric_definition')
    op.drop_index('uq_dimension_value_tenant_code', table_name='dimension_value', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('uq_dimension_value_global_code', table_name='dimension_value', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_table('dimension_value')
    op.drop_table('disclosure')
    op.drop_index('uq_dimension_tenant_code', table_name='dimension', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('uq_dimension_global_code', table_name='dimension', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_table('dimension')
    op.drop_table('standard')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION catalog_check_scope()")
